export const TOUR_DATES = [
  {
    id: 'guatrache-0619',
    date: '19/06',
    fullDate: '2026-06-19',
    venue: 'Next',
    city: 'GUATRACHÉ, LA PAMPA',
    image: '/images/flyers/guatrache-jun.webp',
    ticketUrl: 'https://centralticket.net/Tukixnext',
  },
  {
    id: 'choele-0620',
    date: '20/06',
    fullDate: '2026-06-20',
    venue: 'One Night Clúb',
    city: 'CHOELE CHOEL, RÍO NEGRO',
    image: '/images/flyers/choele-jun.webp',
    ticketUrl: 'https://centralticket.net/Choeletuki1',
  },
  {
    id: 'pigue-0620',
    date: '20/06',
    fullDate: '2026-06-20',
    venue: 'La Previa',
    city: 'PIGÜÉ, BUENOS AIRES',
    image: '/images/flyers/pigue-jun.webp',
    ticketUrl: 'https://centralticket.net/Tukipigue',
  },
  {
    id: 'chascomus-0620',
    date: '20/06',
    fullDate: '2026-06-20',
    venue: 'Mové',
    city: 'CHASCOMÚS, BUENOS AIRES',
    image: '/images/flyers/chascomus-jun.webp',
    ticketUrl: 'https://centralticket.net/Tukixmove',
  },
  {
    id: 'lamadrid-0627',
    date: '27/06',
    fullDate: '2026-06-27',
    venue: 'Garden Point',
    city: 'LA MADRID, BUENOS AIRES',
    image: '/images/flyers/la-madrid-jun.webp',
    ticketUrl: 'https://centralticket.net/Gardenxtuki',
  },
  {
    id: 'rauch-0627',
    date: '27/06',
    fullDate: '2026-06-27',
    venue: '',
    city: 'RAUCH, BUENOS AIRES',
    image: '/images/flyers/rauch-jun.webp',
    ticketUrl: 'https://centralticket.net/Latukirauch',
  },
  {
    id: 'malargue-0627',
    date: '27/06',
    fullDate: '2026-06-27',
    venue: 'Clúb Montana',
    city: 'MALARGÜE, MENDOZA',
    image: '/images/flyers/malargue-jun.webp',
    ticketUrl: 'https://centralticket.net/latukimalargue',
  },
  {
    id: 'rincon-0704',
    date: '04/07',
    fullDate: '2026-07-04',
    venue: 'Clúb Berlín',
    city: 'RINCÓN DE LOS SAUCES, NEUQUÉN',
    image: '/images/flyers/rincon-0704.webp',
    ticketUrl: 'https://centralticket.net/Latukirincon',
  },
  {
    id: 'plottier-0711',
    date: '11/07',
    fullDate: '2026-07-11',
    venue: 'Animal',
    city: 'PLOTTIER, NEUQUÉN',
    image: '/images/flyers/plottier-0711.webp',
    ticketUrl: 'https://centralticket.net/Tukiplotier',
  },
  {
    id: 'pringles-0711',
    date: '11/07',
    fullDate: '2026-07-11',
    venue: 'Área 42',
    city: 'CORONEL PRINGLES, BUENOS AIRES',
    image: '/images/flyers/pringles-0711.webp',
    ticketUrl: 'https://centralticket.net/Tukixpringles',
  },
  {
    id: 'suarez-0718',
    date: '18/07',
    fullDate: '2026-07-18',
    venue: 'Eclipse',
    city: 'CORONEL SUÁREZ, BUENOS AIRES',
    image: '/images/flyers/suarez-0718.webp',
    ticketUrl: 'https://centralticket.net/Suarezamigo',
  },
  {
    id: 'madryn-0718',
    date: '18/07',
    fullDate: '2026-07-18',
    venue: 'Clúb Cero Uno',
    city: 'PUERTO MADRYN, CHUBUT',
    image: '/images/flyers/madryn-1807-logo.webp',
    ticketUrl: 'https://centralticket.net/Madryntuki',
  },
  {
    id: 'roca-0725',
    date: '25/07',
    fullDate: '2026-07-25',
    venue: 'Aquelarre',
    city: 'GENERAL ROCA, RÍO NEGRO',
    image: '/images/flyers/gralroca-25-07.webp',
    ticketUrl: 'https://centralticket.net/Rocaxtuki',
  },
  {
    id: 'rosario-0731',
    date: '31/07',
    fullDate: '2026-07-31',
    venue: 'Jaguar House',
    city: 'ROSARIO, SANTA FE',
    image: '/images/flyers/rosario-31-07.webp',
    ticketUrl: 'https://centralticket.net/Jaguarxtuki',
  },
  {
    id: 'zapala-0807',
    date: '07/08',
    fullDate: '2026-08-07',
    venue: 'Mi Rancho Tropical',
    city: 'ZAPALA, NEUQUÉN',
    image: '/images/flyers/zapala-7-08.webp',
    ticketUrl: 'https://centralticket.net/event/Latukixzapala',
  },
  {
    id: 'palermo-0808',
    date: '08/08',
    fullDate: '2026-08-08',
    venue: 'Laundry Club',
    city: 'PALERMO, CABA',
    image: '/images/flyers/palermo-8-08.webp',
    ticketUrl: 'https://passify.link/invitacion/1358Q0BN6M',
  },
];

export const TWEETS = [
  {
    user: 'marta_perreo',
    initial: 'M',
    handle: '@marta_perreo',
    content:
      'Obras se cae abajo. El último set de reggaeton old school me voló la peluca. ¡Yendooo! 🚀',
  },
  {
    user: 'juancho_tuki',
    initial: 'J',
    handle: '@juancho_tuki',
    content: '¿Alguien tiene entradas de sobra? No me puedo perder esta locura otra vez.',
  },
  {
    user: 'Mateo (Staff)',
    image:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDNNk77zRFc2UocSWBQ2nwDkVhPweEBIRfEjn-gUtvT6O80Q7T3QnYAd7C8wnSjt1ku0Tqn-1tA4b4PBpbVgyVjsKlotx2UijzuNZOajcCwNp_w9T4fp2292bM6peIf5ww8YidZd0a0eIFBS-WdvTMmnuoi5a9TjLKJA0xSs9q1ubPl1RBZrfbLBJtDC8Oz9E-HXd6BXAN5lZAKeqYxKwfjKiCiVk94YlLcwmwJ-GK7frpr-lhw5sTtkthkDxig_K8l7JlFcf9dCH3d',
    handle: 'Staff',
    content: 'Prepárense para las sorpresas que tenemos para Obras. Se pudre todo.',
    isStaff: true,
  },
];

export const TEAM = [
  { name: 'NICO', role: 'Productor y logística', gender: 'm' },
  { name: 'TOMI', role: 'Productor y logística', gender: 'm' },
  { name: 'POLI', role: 'Productor y logística', gender: 'f' },
  { name: 'MARCHU', role: 'Directora de marketing', gender: 'f' },
  { name: 'JUANI', role: 'Productor creativo', gender: 'm' },
  { name: 'FEDU', role: 'Relaciones públicas', gender: 'f' },
  { name: 'JERO', role: 'Difusores', gender: 'm' },
  { name: 'FRAN', role: 'Diseño gráfico', gender: 'm' },
  { name: 'DAI', role: 'Creadora de contenido en TikTok', gender: 'f' },
  { name: 'CHICHE', role: 'Community manager', gender: 'm' },
  { name: 'JUANITA', role: 'Difusores', gender: 'f' },
] as const;

export const FAQS = [
  {
    question: '¿Edad mínima?',
    answer:
      'El ingreso respeta la edad mínima establecida según la normativa local y el venue de cada edición. Puede solicitarse DNI físico o Mi Argentina al ingresar.',
  },
  {
    question: '¿Entradas y devoluciones?',
    answer:
      'Las entradas son válidas únicamente si fueron adquiridas a través de los canales oficiales comunicados por La Tuki en cada fecha. Si comprás entradas por reventa no autorizada, pueden ser rechazadas en el ingreso. En esos casos, la organización no puede hacerse responsable por duplicaciones, estafas o inconvenientes derivados de compras fuera de los medios oficiales. Nuestro consejo: usá siempre los links publicados en nuestras redes.',
  },
  {
    question: '¿Se realizan devoluciones?',
    answer:
      'No se realizan devoluciones en caso de inasistencia del comprador, errores al momento de la compra, confusión en la selección de fecha o ciudad, o cualquier motivo ajeno a la organización. En caso de reintegro, el mismo queda sujeto a lo que comuniquemos oficialmente por nuestras redes sociales.',
  },
];
